name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
jobs:       
  deploy:
    runs-on: ubuntu-latest
    # 해당 레포지토리로 check-out하는 Action을 불러옴
    steps:
    - name: Checkout to repo
      uses: actions/checkout@v2

    # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
    - name: Generate Environment Variables File for Production
      run: |
        echo "GOOGLE_SECRET_KEY=$GOOGLE_SECRET_KEY" >> .env
        echo "NAVER_CLIENT_ID=$NAVER_CLIENT_ID" >> .env
        echo "NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET" >> .env
        echo "CLOUDINARY_URL=$CLOUDINARY_URL" >> .env
        echo "CLOUDINARY_NAME=$CLOUDINARY_NAME" >> .env
        echo "CLOUDINARY_KEY=$CLOUDINARY_KEY" >> .env
        echo "CLOUDINARY_SECRET=$CLOUDINARY_SECRET" >> .env
        echo "DOGCOURSE_URL=$DOGCOURSE_URL" >> .env
        echo "REDIS_HOST=$REDIS_HOST" >> .env
        echo "REDIS_PORT=$REDIS_PORT" >> .env
      env:
        GOOGLE_SECRET_KEY: ${{ secrets.GOOGLE_SECRET_KEY }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
        CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
        CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
        DOGCOURSE_URL: ${{ secrets.DOGCOURSE_URL }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}

    #git hub 계정 접근
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

   
    # Step 3
    - name: Create CodeDeploy Deployment
      id: deploy
      run: |
        aws deploy create-deployment \
        --application-name dogcourse-server \
        --deployment-group-name dogcourse-server-cd1 \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

    